# Generated by Django 4.0.2 on 2022-03-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='birthday',
        ),
    ]
